import { initializeApp } from "https://www.gstatic.com/firebasejs/12.17.0/firebase-app.js";
import { getAuth, onAuthStateChanged, signInWithEmailAndPassword, signOut } from "https://www.gstatic.com/firebasejs/12.17.0/firebase-auth.js";
import { getFirestore, doc, onSnapshot, setDoc, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.17.0/firebase-firestore.js";

const firebaseConfig = { apiKey:"AIzaSyASDU7WFHjIVr6sWt1sVrcJtY2xdEq-PIc", authDomain:"skolschema-2650a.firebaseapp.com", projectId:"skolschema-2650a", storageBucket:"skolschema-2650a.firebasestorage.app", messagingSenderId:"16889883202", appId:"1:16889883202:web:c50aaac1190ab39abddbdb", measurementId:"G-5Q6F7TX3GL" };
const firebaseApp = initializeApp(firebaseConfig), auth = getAuth(firebaseApp), db = getFirestore(firebaseApp);
const adminUid = "7BZrSETmpabYd3aXd2JTIPuVRVn1";
const days = ["Måndag", "Tisdag", "Onsdag", "Torsdag", "Fredag"];
const subjectInfo = {
  SV:["Svenska","📝","#f51d24"], MA:["Matte","📐","#2049e8"], NO:["NO","⚗️","#058344"], SL:["Slöjd","🪚","#0eef13"], MU:["Musik","🎧","#6e0575"], SO:["SO","🗺️","#fff200"], HKK:["Hemkunskap","🥘","#a56a18"], IDH:["Idrott","🏃","#ef78ee"], EN:["Engelska","💬","#8a0991"], BL:["Bild","🖌️","#a56a18"], TK:["Teknik","🔧","#058344"], RAST:["Rast","☀️","#72c58a"], LUNCH:["Lunch","🍽️","#d9dde7"], SPRÅK:["Språk / elevens val","🗣️","#ff7c3d"]
};
const schedules = {
  sixten: [
    [["08:10","09:10","SO",""],["09:15","10:00","BL",""],["10:20","11:10","IDH",""],["11:25","11:50","SV",""],["11:50","12:10","LUNCH",""],["12:40","13:40","MA",""],["13:55","15:00","NO",""]],
    [["08:10","09:00","SV",""],["09:05","10:00","IDH",""],["10:20","11:15","SO",""],["11:20","11:50","SV",""],["11:50","12:10","LUNCH",""],["12:40","13:20","EN",""],["13:25","14:10","MA",""]],
    [["08:10","08:55","SO",""],["09:00","10:00","SV",""],["10:20","11:05","MA",""],["11:10","11:50","EN",""],["11:50","12:10","LUNCH",""],["12:45","14:05","SL",""]],
    [["08:10","09:20","HKK",""],["09:35","10:50","HKK",""],["11:10","11:50","MA",""],["11:50","12:10","LUNCH",""],["12:40","13:40","NO",""],["13:40","14:10","TK",""]],
    [["08:10","09:05","SV",""],["09:10","10:00","SO",""],["10:20","11:05","MA",""],["11:10","11:50","EN",""],["11:50","12:10","LUNCH",""],["12:45","14:10","SPRÅK","Elevens val"]]
  ],
  ilse: [
    [["08:10","09:30","SV",""],["10:00","11:15","MA",""],["11:15","11:45","LUNCH",""],["12:25","13:55","NO",""]],
    [["08:10","09:35","SL",""],["10:00","10:30","SV",""],["10:30","11:15","MU",""],["11:15","11:45","LUNCH",""],["12:25","13:05","MA",""],["13:05","14:10","SV",""]],
    [["08:10","08:50","SV",""],["09:00","09:40","IDH",""],["10:15","11:15","MA",""],["11:15","11:45","LUNCH",""],["12:25","13:30","SO",""],["13:30","14:10","SV",""]],
    [["08:10","08:50","EN",""],["09:00","09:30","BL",""],["10:00","10:40","TK",""],["10:40","11:15","MA",""],["11:15","11:45","LUNCH",""],["12:25","13:25","SO",""],["13:25","14:10","SV",""]],
    [["08:20","09:00","IDH",""],["09:15","09:30","SV",""],["10:00","10:40","SV",""],["10:40","11:15","MA",""],["11:15","11:45","LUNCH",""],["12:25","14:10","SV",""]]
  ]
};
const settingsKey = "mitt-skolschema-installningar-v1";
const accents = { purple: "#5b47e5", blue: "#2378df", green: "#058344", coral: "#e75a5a" };
const defaultSettings = () => ({ accent: "purple", display: "both" });
let childSettings = { sixten: defaultSettings(), ilse: defaultSettings() };
const todayIndex = new Date().getDay() - 1;
let child = null, view = "day", chosenDay = todayIndex;
if (chosenDay < 0 || chosenDay > 4) chosenDay = 0;
const $ = s => document.querySelector(s);
function settingsForChild() { return childSettings[child] || defaultSettings(); }
function saveSettings() { localStorage.setItem(settingsKey, JSON.stringify(childSettings)); }
function applyAccent() { document.documentElement.style.setProperty("--purple", accents[settingsForChild().accent] || accents.purple); }
function validWeek(week) { return Array.isArray(week) && week.length === 5 && week.every(day => Array.isArray(day) && day.every(lesson => Array.isArray(lesson) && lesson.length >= 3)); }
function escapeHtml(value) { return String(value).replace(/[&<>'"]/g, char => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char])); }
const weekKeys=["monday","tuesday","wednesday","thursday","friday"];
function toFirestoreWeek(week){return Object.fromEntries(weekKeys.map((key,index)=>[key,week[index].map(([start,end,code,detail])=>({start,end,code,detail:detail||""}))]));}
function fromFirestoreWeek(value){if(!value||typeof value!=="object"||Array.isArray(value))return null;const week=weekKeys.map(key=>Array.isArray(value[key])?value[key].map(lesson=>[lesson.start,lesson.end,lesson.code,lesson.detail||""]):[]);return validWeek(week)?week:null;}
const installButton = $("#install-app"), installHelp = $("#install-help");
let installEvent;
const onPhone = /iPhone|iPad|iPod|Android/i.test(navigator.userAgent);
const onIos = /iPhone|iPad|iPod/i.test(navigator.userAgent);
const installed = window.matchMedia("(display-mode: standalone)").matches || window.navigator.standalone;
const shareIcon = `<span class="ios-share-icon" aria-label="Dela"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 15V3m0 0-4 4m4-4 4 4M5 10v9h14v-9"/></svg></span>`;
if (onIos && !installed) { installHelp.innerHTML = `Installera: öppna sidan i Safari, tryck på ${shareIcon} och välj “Lägg till på hemskärmen”.`; installHelp.classList.remove("hidden"); }
if (!onPhone) { installHelp.textContent = "Öppna appen på en telefon för att installera den på hemskärmen."; installHelp.classList.remove("hidden"); }
window.addEventListener("beforeinstallprompt", event => { event.preventDefault(); installEvent = event; installButton.classList.remove("hidden"); });
installButton.onclick = async () => { if (!installEvent) return; installEvent.prompt(); await installEvent.userChoice; installEvent = null; installButton.classList.add("hidden"); };
window.addEventListener("appinstalled", () => { installHelp.textContent = "Appen är installerad på hemskärmen."; installHelp.classList.remove("hidden"); installButton.classList.add("hidden"); });
function info(code) { return subjectInfo[code] || [code, "📘", "#8d92a7"]; }
const groupAlternatives = { sixten: { 3: [["08:10","08:40","SV",""],["08:45","09:25","MU",""],["09:25","10:15","MU",""],["10:20","10:50","SV",""]] } };
const fixedBreaks = { sixten: [[["10:00","10:20","RAST",""],["12:10","12:40","RAST",""]],[["10:00","10:20","RAST",""],["12:10","12:40","RAST",""]],[["10:00","10:20","RAST",""],["12:10","12:45","RAST",""]],[["10:50","11:10","RAST",""],["12:10","12:40","RAST",""]],[["10:00","10:20","RAST",""],["12:10","12:45","RAST",""]]], ilse: [[["09:30","10:00","RAST",""],["11:45","12:25","RAST",""]],[["09:35","10:00","RAST",""],["11:45","12:25","RAST",""]],[["09:40","10:15","RAST",""],["11:45","12:25","RAST",""]],[["09:30","10:00","RAST",""],["11:45","12:25","RAST",""]],[["09:30","10:00","RAST",""],["11:45","12:25","RAST",""]]] };
function dayLessons(childId, dayIndex) { const regular=schedules[childId][dayIndex] || [], extras=[...(fixedBreaks[childId]?.[dayIndex] || []),...(groupAlternatives[childId]?.[dayIndex] || [])]; return [...regular,...extras.filter(extra=>!regular.some(lesson=>lesson[0]===extra[0]&&lesson[1]===extra[1]&&lesson[2]===extra[2]))].sort((a,b)=>a[0].localeCompare(b[0])); }
function overlaps(a,b) { return a[0] < b[1] && b[0] < a[1]; }
function renderDayLessons(lessons) { const remaining=[...lessons], sections=[]; while(remaining.length){const first=remaining.shift(), group=[first];let changed=true;while(changed){changed=false;for(let i=remaining.length-1;i>=0;i--)if(group.some(item=>overlaps(item,remaining[i]))){group.push(...remaining.splice(i,1));changed=true;}}group.sort((a,b)=>a[0].localeCompare(b[0]));sections.push(group);}return sections.map(group=>{if(group.length===1)return lessonCard(group[0]);const hkk=group.filter(item=>item[2]==="HKK"), other=group.filter(item=>item[2]!=="HKK");return hkk.length&&other.length?`<section class="parallel-group"><div class="parallel-routes"><div class="parallel-route">${hkk.map(item=>lessonCard(item)).join("")}</div><span class="parallel-or">eller</span><div class="parallel-route">${other.map(item=>lessonCard(item)).join("")}</div></div></section>`:`<section class="parallel-group"><div class="parallel-list">${group.map(item=>lessonCard(item)).join("")}</div></section>`;}).join(""); }
function minutesSinceMidnight(time) { const [hours, minutes] = time.split(":").map(Number); return hours * 60 + minutes; }
function renderWeekLessons(lessons) { const remaining=[...lessons], sections=[]; while(remaining.length){const first=remaining.shift(), group=[first];let changed=true;while(changed){changed=false;for(let i=remaining.length-1;i>=0;i--)if(group.some(item=>overlaps(item,remaining[i]))){group.push(...remaining.splice(i,1));changed=true;}}group.sort((a,b)=>a[0].localeCompare(b[0]));sections.push(group);}return sections.map(group=>{if(group.length===1)return lessonCard(group[0],true);const hkk=group.filter(item=>item[2]==="HKK"), other=group.filter(item=>item[2]!=="HKK");return hkk.length&&other.length?`<section class="week-parallel"><div class="week-route">${hkk.map(item=>lessonCard(item,true)).join("")}</div><span class="week-or">eller</span><div class="week-route">${other.map(item=>lessonCard(item,true)).join("")}</div></section>`:group.map(item=>lessonCard(item,true)).join("");}).join(""); }
function updateNextLesson() {
  const container = $("#next-lesson");
  if (!child) { container.innerHTML = ""; return; }
  const reminder = view === "day" ? packReminder() : "";
  const actualDay = new Date().getDay() - 1;
  if (actualDay < 0 || actualDay > 4) { container.innerHTML = `<article class="next-card finished"><p class="eyebrow">SKOLDAGEN</p><h2>Ingen skola idag</h2><p>Vi ses nästa skoldag.</p></article>${reminder}`; return; }
  const now = new Date(), nowMinutes = now.getHours() * 60 + now.getMinutes(), today = dayLessons(child,actualDay);
  const current = today.find(lesson => minutesSinceMidnight(lesson[0]) <= nowMinutes && minutesSinceMidnight(lesson[1]) > nowMinutes);
  const upcoming = today.find(lesson => lesson[2] !== "LUNCH" && minutesSinceMidnight(lesson[0]) > nowMinutes);
  const lunch = today.find(lesson => lesson[2] === "LUNCH");
  const last = [...today].filter(lesson => lesson[2] !== "LUNCH").at(-1);
  const nextDay = actualDay === 4 ? 0 : actualDay + 1;
  const tomorrowFirst = dayLessons(child,nextDay).find(lesson => lesson[2] !== "LUNCH");
  const summary = `<div class="quick-facts"><span>🍽️ Lunch ${lunch?.[0] || ""}</span><span>🏁 Slutar ${last?.[1] || ""}</span><span>→ ${days[nextDay]} ${tomorrowFirst?.[0] || ""}</span></div>`;
  if (current) { const [name, icon] = info(current[2]), remaining = minutesSinceMidnight(current[1]) - nowMinutes; container.innerHTML = `<article class="next-card"><p class="eyebrow">JUST NU</p><h2>${icon} ${name} · till ${current[1]}</h2><p class="countdown">Slutar om ${remaining} min</p>${summary}</article>${reminder}`; return; }
  if (!upcoming) { container.innerHTML = `<article class="next-card finished"><p class="eyebrow">SKOLDAGEN</p><h2>Dagens skoldag är slut</h2><p>Fint jobbat idag.</p>${summary}</article>${reminder}`; return; }
  const [name, icon] = info(upcoming[2]), remaining = minutesSinceMidnight(upcoming[0]) - nowMinutes;
  container.innerHTML = `<article class="next-card"><p class="eyebrow">NÄSTA LEKTION</p><h2>${icon} ${name} · ${upcoming[0]}</h2><p class="countdown">${name} börjar om ${remaining} min</p>${summary}</article>${reminder}`;
}
function lessonCard(lesson, small=false) { const [start,end,code,detail] = lesson, [name,icon,color] = info(code), display = settingsForChild().display; const time = display === "icons" ? "" : `<time>${start}${small ? "–" : "<br>– "}${end}</time>`; const iconHtml = display === "times" ? "" : `<span class="subject-icon" aria-hidden="true">${icon}</span>`; const timeCards = display === "icons" ? "" : `<div class="lesson-times" aria-label="Tid ${start} till ${end}"><b>${start}</b><span aria-hidden="true">–</span><b>${end}</b></div>`; return small ? `<article class="week-lesson ${display}" style="--subject:${color}">${time}<strong>${name}</strong>${detail?`<small>${detail}</small>`:""}</article>` : `<article class="lesson ${display}" style="--subject:${color}"><div class="lesson-info">${timeCards}<div class="lesson-main">${iconHtml}<div><h3>${name}</h3>${detail?`<p>${detail}</p>`:""}</div></div></div></article>`; }
function packReminder() {
  const nextDay = chosenDay === 4 ? 0 : chosenDay + 1;
  if (!dayLessons(child,nextDay).some(lesson => lesson[2] === "IDH")) return "";
  return `<aside class="pack-reminder"><span aria-hidden="true">🏃</span><div><p class="eyebrow">I MORGON · ${days[nextDay].toUpperCase()}</p><h2>Kom ihåg idrottskläder</h2><p>Packa gympakläder och inneskor till i morgon.</p></div></aside>`;
}
function render() {
  const name = child === "sixten" ? "Sixten" : "Ilse"; const data = schedules[child].map((_,index)=>dayLessons(child,index));
  applyAccent();
  $("#child-label").textContent = `${name.toUpperCase()}S SCHEMA`; $("#schedule-title").textContent = `Hej ${name}!`;
  document.querySelectorAll(".view-toggle button").forEach(b => b.classList.toggle("active",b.dataset.view===view));
  if (view === "day") { const isToday = chosenDay === todayIndex; $("#schedule-content").innerHTML = `<div class="day-heading"><button class="day-arrow" data-step="-1" ${chosenDay === 0 ? "disabled" : ""} aria-label="Visa föregående dag">←</button><h2 class="day-title">${isToday ? "IDAG · " : ""}${days[chosenDay]}</h2><button class="day-arrow" data-step="1" ${chosenDay === days.length - 1 ? "disabled" : ""} aria-label="Visa nästa dag">→</button></div><div class="day-list">${renderDayLessons(data[chosenDay]) || '<p class="empty">Inga lektioner idag.</p>'}</div>`; }
  else { const used=[...new Set(data.flat().map(x=>x[2]))]; $("#schedule-content").innerHTML = `<p class="week-hint">Tryck på dagens rubrik för att se den närmare.</p><div class="week-grid">${data.map((day,i)=>`<section class="week-day ${i === todayIndex ? "is-today" : ""}"><button class="week-day-heading" data-week-day="${i}" aria-label="Visa ${days[i]}"><h2>${days[i]}${i === todayIndex ? '<span class="today-badge">IDAG</span>' : ""}</h2><span aria-hidden="true">→</span></button><span class="week-count">${day.length} pass</span>${renderWeekLessons(day)}</section>`).join("")}</div><div class="legend">${used.map(c=>{const [n,,color]=info(c);return `<span style="--subject:${color}">${n}</span>`}).join("")}</div>`; }
  updateNextLesson();
}
document.addEventListener("click", e => { const childBtn=e.target.closest("[data-child]"); if(childBtn){child=childBtn.dataset.child; theme=settingsForChild().theme || theme; applyTheme(theme); $("#home").classList.add("hidden"); $("#schedule").classList.remove("hidden"); render();} const weekDay=e.target.closest("[data-week-day]"); if(weekDay){chosenDay=+weekDay.dataset.weekDay;view="day";render();window.scrollTo({ top: 0, behavior: "smooth" });} const step=e.target.closest("[data-step]"); if(step && !step.disabled){chosenDay+=+step.dataset.step;render();window.scrollTo({ top: 0, behavior: "smooth" });} const viewBtn=e.target.closest("[data-view]"); if(viewBtn){view=viewBtn.dataset.view;if(view === "day" && todayIndex >= 0 && todayIndex < 5)chosenDay=todayIndex;render();} });
document.querySelectorAll(".view-toggle [data-view]").forEach(button => button.addEventListener("click", () => { view=button.dataset.view; if(view === "day" && todayIndex >= 0 && todayIndex < 5)chosenDay=todayIndex; render(); }));
$("#go-home").onclick=()=>{$("#schedule").classList.add("hidden");$("#home").classList.remove("hidden")};
function applyTheme(theme) { document.body.classList.toggle("dark", theme === "dark"); document.querySelector('meta[name="theme-color"]').content = theme === "dark" ? "#171827" : "#5b47e5"; $("#theme-toggle").textContent = theme === "dark" ? "☀" : "◐"; }
let theme = localStorage.getItem("mitt-skolschema-tema") || (window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light");
applyTheme(theme);
async function saveAppearance(childId){const settings=childSettings[childId];await setDoc(doc(db,"utseende",childId),{accent:settings.accent,display:settings.display,theme:settings.theme||"light"},{merge:true});}
$("#theme-toggle").onclick=async()=>{if(!child)return;theme=theme === "dark" ? "light" : "dark";localStorage.setItem("mitt-skolschema-tema",theme);settingsForChild().theme=theme;saveSettings();applyTheme(theme);try{await saveAppearance(child);}catch{alert("Kunde inte synka inställningen till Firebase.");}};
const settingsDialog=$("#settings-dialog");
function refreshSettingsDialog() { const settings=settingsForChild(); document.querySelectorAll("[data-accent]").forEach(button => button.classList.toggle("selected", button.dataset.accent === settings.accent)); document.querySelectorAll("[data-display]").forEach(button => button.classList.toggle("selected", button.dataset.display === settings.display)); }
$("#open-settings").onclick=()=>{refreshSettingsDialog();settingsDialog.showModal();};
$("#accent-choices").onclick=async e=>{const button=e.target.closest("[data-accent]");if(!button)return;settingsForChild().accent=button.dataset.accent;saveSettings();applyAccent();refreshSettingsDialog();render();try{await saveAppearance(child);}catch{alert("Kunde inte synka inställningen till Firebase.");}};
$("#display-choices").onclick=async e=>{const button=e.target.closest("[data-display]");if(!button)return;settingsForChild().display=button.dataset.display;saveSettings();refreshSettingsDialog();render();try{await saveAppearance(child);}catch{alert("Kunde inte synka inställningen till Firebase.");}};
try {const saved=JSON.parse(localStorage.getItem(settingsKey));["sixten","ilse"].forEach(name => { if (saved?.[name]) childSettings[name] = { ...defaultSettings(), accent: saved[name].accent, display: saved[name].display, theme: saved[name].theme }; });}catch{}
let signedInUser=null;
const scheduleHistory={sixten:{},ilse:{}};
function cloneWeek(week){return week.map(day=>day.map(lesson=>[...lesson]));}
function syncChild(childId) { onSnapshot(doc(db,"skolschema",childId), snapshot => { const data=snapshot.data()||{},week=fromFirestoreWeek(data.week);if(week)schedules[childId]=week;scheduleHistory[childId]=data.history&&typeof data.history==="object"?data.history:{};if(child===childId)render();if(adminDialog?.open&&editorState?.child===childId)renderEditor(); }, () => {}); }
function syncAppearance(childId){onSnapshot(doc(db,"utseende",childId),snapshot=>{const preferences=snapshot.data();if(!preferences)return;childSettings[childId]={...defaultSettings(),accent:preferences.accent||"purple",display:preferences.display||"both",theme:preferences.theme||"light"};saveSettings();if(child===childId){theme=childSettings[childId].theme;applyTheme(theme);render();}},()=>{});}
const adminDialog=$("#admin-dialog"), editorState={child:"sixten",day:0,code:"SV",editing:null};
syncChild("sixten"); syncChild("ilse"); syncAppearance("sixten"); syncAppearance("ilse");
function renderHistory(){const entries=Object.entries(scheduleHistory[editorState.child]||{}).filter(([,version])=>fromFirestoreWeek(version.week)).sort((a,b)=>String(b[1].savedAt).localeCompare(String(a[1].savedAt)));$("#history-list").innerHTML=entries.length?entries.map(([id,version])=>`<div class="history-row"><span>${new Date(version.savedAt).toLocaleString("sv-SE",{dateStyle:"short",timeStyle:"short"})}</span><button type="button" data-restore="${id}">Återställ</button></div>`).join(""):`<p class="history-empty">Ingen tidigare version ännu.</p>`;}
function renderEditor() { const lessons=schedules[editorState.child][editorState.day]; $("#editor-child").value=editorState.child;$("#editor-day").value=editorState.day;$("#editor-lessons").innerHTML=lessons.length?lessons.map((lesson,index)=>{const [name,icon,color]=info(lesson[2]);return `<article class="editor-lesson" style="--subject:${color}"><button type="button" data-edit="${index}"><time>${lesson[0]}–${lesson[1]}</time><strong>${icon} ${name}</strong>${lesson[3]?`<small>${escapeHtml(lesson[3])}</small>`:""}</button><button type="button" data-delete="${index}" aria-label="Ta bort ${name}">×</button></article>`;}).join(""):`<p class="empty">Inga lektioner ännu.</p>`;$("#subject-blocks").innerHTML=Object.entries(subjectInfo).map(([code,[name,icon,color]])=>`<button type="button" data-subject="${code}" class="subject-block ${editorState.code===code?"selected":""}" style="--subject:${color}">${icon} ${name}</button>`).join("");renderHistory(); }
function resetEditorForm(){editorState.editing=null;$("#lesson-form-title").textContent="Lägg till lektion";$("#save-lesson").textContent="Lägg till lektion";$("#cancel-lesson").classList.add("hidden");$("#lesson-start").value="";$("#lesson-end").value="";$("#lesson-detail").value="";}
function editorMessage(text, error=false){const element=$("#editor-message");element.textContent=text;element.classList.toggle("is-error",error);}
async function saveWeek(childId,previousWeek){try{const history={...scheduleHistory[childId]};if(previousWeek){history[`${Date.now()}-${Math.random().toString(36).slice(2,6)}`]={savedAt:new Date().toISOString(),week:toFirestoreWeek(previousWeek)};}const ids=Object.keys(history).sort((a,b)=>String(history[b].savedAt).localeCompare(String(history[a].savedAt)));ids.slice(10).forEach(id=>delete history[id]);await setDoc(doc(db,"skolschema",childId),{week:toFirestoreWeek(schedules[childId]),history,updatedAt:serverTimestamp()},{merge:true});scheduleHistory[childId]=history;editorMessage("Ändringen är sparad!");}catch(error){console.error("Kunde inte spara schema",error);const code=error.code || "okänt fel";editorMessage(code === "permission-denied" ? "Firebase nekade ändringen. Kontrollera Firestore-regeln och att du är inloggad med rätt konto." : `Kunde inte spara (${code}). ${error.message || "Försök igen."}`,true);throw error;}}
function showEditor(){ $("#login-screen").classList.add("hidden");$("#editor-screen").classList.remove("hidden");editorState.child=child||"sixten";editorState.day=chosenDay;resetEditorForm();renderEditor();}
$("#open-admin").onclick=()=>{adminDialog.showModal();if(signedInUser?.uid===adminUid)showEditor();else{$("#login-screen").classList.remove("hidden");$("#editor-screen").classList.add("hidden");}};
$("#close-admin").onclick=()=>adminDialog.close();
$("#login-form").onsubmit=async e=>{e.preventDefault();const message=$("#login-message");try{await signInWithEmailAndPassword(auth,$("#login-email").value,$("#login-password").value);message.textContent="";}catch{message.textContent="Kunde inte logga in. Kontrollera e-post och lösenord.";}};
onAuthStateChanged(auth,user=>{signedInUser=user;if(user && user.uid===adminUid){if(adminDialog.open)showEditor();return;}if(adminDialog.open){$("#editor-screen").classList.add("hidden");$("#login-screen").classList.remove("hidden");}if(user)$("#login-message").textContent="Det här kontot saknar rättighet att ändra schemat.";});
$("#editor-child").onchange=e=>{editorState.child=e.target.value;resetEditorForm();renderEditor();};$("#editor-day").onchange=e=>{editorState.day=Number(e.target.value);resetEditorForm();renderEditor();};
$("#subject-blocks").onclick=e=>{const button=e.target.closest("[data-subject]");if(button){editorState.code=button.dataset.subject;renderEditor();}};
$("#editor-lessons").onclick=async e=>{const del=e.target.closest("[data-delete]");if(del){const day=schedules[editorState.child][editorState.day], backup=cloneWeek(schedules[editorState.child]);day.splice(Number(del.dataset.delete),1);try{await saveWeek(editorState.child,backup);resetEditorForm();renderEditor();if(child===editorState.child)render();}catch{schedules[editorState.child]=backup;renderEditor();}return;}const edit=e.target.closest("[data-edit]");if(!edit)return;const lesson=schedules[editorState.child][editorState.day][Number(edit.dataset.edit)];editorState.editing=Number(edit.dataset.edit);editorState.code=lesson[2];$("#lesson-start").value=lesson[0];$("#lesson-end").value=lesson[1];$("#lesson-detail").value=lesson[3];$("#lesson-form-title").textContent="Ändra lektion";$("#save-lesson").textContent="Spara ändring";$("#cancel-lesson").classList.remove("hidden");renderEditor();};
$("#lesson-form").onsubmit=async e=>{e.preventDefault();const start=$("#lesson-start").value,end=$("#lesson-end").value;if(end<=start){editorMessage("Sluttiden måste vara efter starttiden.",true);return;}const backup=cloneWeek(schedules[editorState.child]),day=schedules[editorState.child][editorState.day],lesson=[start,end,editorState.code,$("#lesson-detail").value.trim()];if(editorState.editing===null)day.push(lesson);else day[editorState.editing]=lesson;day.sort((a,b)=>a[0].localeCompare(b[0]));try{await saveWeek(editorState.child,backup);resetEditorForm();renderEditor();if(child===editorState.child)render();}catch{schedules[editorState.child]=backup;renderEditor();}};
$("#cancel-lesson").onclick=()=>{resetEditorForm();renderEditor();};$("#save-complete-schedule").onclick=async()=>{const name=editorState.child==="sixten"?"Sixten":"Ilse";if(!confirm(`Spara hela ${name}s schema inklusive raster och grupppass till Firebase?`))return;const backup=cloneWeek(schedules[editorState.child]);schedules[editorState.child]=schedules[editorState.child].map((_,dayIndex)=>dayLessons(editorState.child,dayIndex));try{await saveWeek(editorState.child,backup);resetEditorForm();renderEditor();if(child===editorState.child)render();}catch{schedules[editorState.child]=backup;renderEditor();}};$("#new-term").onclick=async()=>{const name=editorState.child==="sixten"?"Sixten":"Ilse";if(!confirm(`Starta ny termin för ${name}? Det nuvarande schemat ersätts.`))return;const backup=cloneWeek(schedules[editorState.child]);schedules[editorState.child]=Array.from({length:5},()=>[]);try{await saveWeek(editorState.child,backup);resetEditorForm();renderEditor();if(child===editorState.child)render();}catch{schedules[editorState.child]=backup;renderEditor();}};$("#history-list").onclick=async e=>{const button=e.target.closest("[data-restore]");if(!button)return;const version=scheduleHistory[editorState.child][button.dataset.restore],week=fromFirestoreWeek(version?.week);if(!week)return;if(!confirm("Återställ den här tidigare versionen? Det nuvarande schemat sparas också i historiken."))return;const backup=cloneWeek(schedules[editorState.child]);schedules[editorState.child]=cloneWeek(week);try{await saveWeek(editorState.child,backup);resetEditorForm();renderEditor();if(child===editorState.child)render();}catch{schedules[editorState.child]=backup;renderEditor();}};$("#sign-out").onclick=async()=>{await signOut(auth);$("#editor-screen").classList.add("hidden");$("#login-screen").classList.remove("hidden");$("#login-password").value="";$("#login-message").textContent="Du är utloggad.";};
setInterval(updateNextLesson, 30000);
if ("serviceWorker" in navigator) window.addEventListener("load", () => navigator.serviceWorker.register("./sw.js"));
